
services:
  db:
    image: mysql:8.0
    container_name: mysql_db # Nombre fijo
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306" # Puerto alternativo
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -ppassword
      interval: 5s
      timeout: 10s
      retries: 20
    networks:
      - app_net

  app:
    build: .
    command: ["node", "--no-deprecation", "src/app.js"] 
    environment:
     - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=notices_db
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    networks:
      - app_net

networks:
  default:
    name: notices-board-net
    driver: bridge
