
services:
  db:
    image: mysql:8.0
    container_name: mysql_db # Nombre fijo
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306" # Puerto alternativo
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -ppassword
      interval: 5s
      timeout: 10s
      retries: 20
    networks:
      - app_net

  app:
    build: .
    environment:
      RUNNING_IN_DOCKER: 'true'
      DB_HOST: mysql_db
      NODE_ENV: test
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.25.0.0/16" # Nueva red exclusiva
