version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: notices_db  # Cambiado de "test_db" para coincidir con la app
    ports:
      - "3306:3306"  # Puerto estándar de MySQL
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=password  # Corregido "--password"
      interval: 5s
      timeout: 10s
      retries: 20
    networks:
      - app_net

  app:
    build: .
    command: ["node", "--no-deprecation", "src/app.js"]  # Corregido "-no-deprecation"
    environment:
      MODE: development  # Corregido "MODE_FMY-development"
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: notices_db
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net

networks:
  app_net:
    name: notices-board-net
    external: false
    driver: bridge
